{% set name = "ntplib" %}
{% set version = "0.3.4" %}
{% set sha256 = "63b99b0ac670f8283b8d8e5cf75aab1d0d9f62e17d38d1fedc4291e1ce8bd052" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-py3-none-any.whl
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed  .
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    
test:
  imports:
    - ntplib
  
about:
  home: https://pypi.org/project/ntplib/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'This module offers a simple interface to query NTP servers from Python.'
  description: |
    It also provides utility functions to translate NTP fields values to text (mode, leap indicator…). Since it’s pure Python, and only depends on core modules, it should work on any platform with a Python implementation.
  
extra:
  recipe-maintainers:
    - iparask
